version: '3.8'

services:
  postgresql:
    image: postgres:16.3
    environment:
      - POSTGRES_USER=ExamManager
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=exammanager
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: exam-mgmt-image
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/exammanager
      - SPRING_DATASOURCE_USERNAME=ExamManager
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - '8085:8080'
    depends_on:
      postgresql:
        condition: service_healthy

volumes:
  postgres_data:
