package tn.fst.exam_manager.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SessionTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionTypeAllPropertiesEquals(SessionType expected, SessionType actual) {
        assertSessionTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertSessionTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionTypeAllUpdatablePropertiesEquals(SessionType expected, SessionType actual) {
        assertSessionTypeUpdatableFieldsEquals(expected, actual);
        assertSessionTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionTypeAutoGeneratedPropertiesEquals(SessionType expected, SessionType actual) {
        assertThat(expected)
            .as("Verify SessionType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionTypeUpdatableFieldsEquals(SessionType expected, SessionType actual) {
        assertThat(expected)
            .as("Verify SessionType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionTypeUpdatableRelationshipsEquals(SessionType expected, SessionType actual) {
        // empty method
    }
}
