name: Maven Test, Build, Publish, SonarQube Analysis, and Docker

on:
  push:
    branches:
      - develop # Trigger the workflow when changes are pushed to the develop branch
  workflow_dispatch: # Allows manual triggering of the workflow

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    environment: dev # Specify the environment here

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Matches the id in settings.xml
          settings-path: ${{ github.workspace }} # Location of the settings.xml file

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Unit Test Stage
      - name: Run Unit Tests
        run: mvn test --file pom.xml

      # Integration Test Stage
      - name: Run Integration Tests
        run: mvn verify --file pom.xml

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Echo SONAR_HOST_URL
        run: echo "SONAR_HOST_URL is:" ${{ secrets.SONAR_HOST_URL }}

      - name: Run SonarCloud Analysis
        run: |
          mvn -X sonar:sonar -Dsonar.projectKey="FaderFtw_Exam-Management-System" -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION_KEY }} -Dsonar.host.url="https://sonarcloud.io" -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION_KEY: ${{ secrets.SONAR_ORGANIZATION_KEY }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Publish to GitHub Packages Apache Maven
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -DskipTests -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Docker Build and Push to GitHub Container Registry
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} # Use GitHub username
          password: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token for authentication

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image to GHCR
        id: build-and-push-ghcr
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
